### ISSUE TITLE
Invalid UUID or filename

### ISSUE THREAD

**Issue by nurogenic** [phase2/homebrew-devtools#1]
Hey Guys,

`error: Invalid UUID or filename "/Users/don/.docker/machine/machines/dev/boot2docker.iso"`

Looks like the devtools cli is trying to pull from a docker repo link that is incorrect so no boot2docker.iso file can be downloaded. I don't know where to leave this issue because I've been denied access to the bitbucket link in your documentation. https://bitbucket.org/phase2tech/devtools-cli/src/default/docs/index.md 

I think the request https://github.com/docker/docker/releases/tag/v17.03.0 is supposed to be https://github.com/docker/docker/releases/tag/v17.03.0-ce

**Comment by febbraro** [comment]
Thanks for the report. I'll check it out, the new version change (1.13.1 to 17.03.0-ce) is the likely cause for this.  Just as an FYI, we have migrated/renamed devtools to a tool called Outrigger which is entirely public.

The new docs are here: https://docs.outrigger.sh

The code is largely the same, so you will likely still see the same problem, but we are migrating to an entirely open source toolset.

**Comment by nurogenic** [comment]
Sounds great will take a look. Thanks.

**Comment by febbraro** [comment]
This was fixed in rig 1.2.1 which is now published to Homebrew.
